AWSTemplateFormatVersion: 2010-09-09
Description: >- 
  AWSBackup multi region template for AWSBackup osaka
Resources:
  BackupVaultOsaka:
    Type: "AWS::Backup::BackupVault"
    DeletionPolicy: Delete
    Properties:
      BackupVaultName: "OsakaVault"
      # EncryptionKeyArn: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/ca3bbc73-6343-468e-a86f-bcfac18af97a"

Outputs:
  BackupVaultOsakaArn:
    Value: !GetAtt BackupVaultOsaka.BackupVaultArn

